version: '3'
services:
  rabbitmq:
    hostname: "my-rabbit"
    image: rabbitmq:3-management
    ports:
     - "9090:15672"
     - "5672:5672"
  monitoring-framework:
    hostname: "monitoring-framework"
    image: ckrieger/monitoring-framework:latest  
    ports: 
      - "8080:8080"