/*
 * generated by Xtext 2.12.0
 */
package de.iaas.grossmann.ccpl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CCPLStandaloneSetup extends CCPLStandaloneSetupGenerated {

	def static void doSetup() {
		new CCPLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
