/*
 * generated by Xtext 2.12.0
 */
package de.iaas.grossmann.ccpl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CCPLRuntimeModule extends AbstractCCPLRuntimeModule {
}
